### ISSUE TITLE
Ausführlichere Meldung wenn keine ISBN gefunden wird

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#105]
Bei einer Suche nach einer PPN wird im ersten Schritt die ISBN herausgesucht und dann im zweiten Schritt damit in allen Veründen gesucht. Falls aber keine ISBN vorhanden ist, dann erscheint die knappe Fehlermeldung `Keine zugehörige ISBN gefunden!` mit der Benutzer nicht unbedingt etwas anfangen können. Z.B. http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?ppn=HT004808001&verbund=HBZ . Hier könnte man etwas ausführen, etwa mit einer Ergänzung `Ohne ISBN wird aber keine Suche in den verschiedenen Verbünden angesteuert.`

HT @vossviola : https://twitter.com/v_i_o_l_a/status/1100671378414538753

**Comment by vossviola** [comment]
Die Phrase findet sich in suche.html in Zeile 123.
https://github.com/UB-Mannheim/malibu/blob/master/isbn/suche.html
Ich habe mich mal an einem Pull Request versucht. :)
