### ISSUE TITLE
K10Plus-OPAC

### ISSUE THREAD

**Issue by tkees** [UB-Mannheim/malibu#113]
Hallo,
ich bin nicht sicher, ob ein wirklicher K10Plus-OPAC vorgesehen ist. Soweit ich es sehe, gibt es bisher einen GVK mit erweiterten Beständen und den früheren SWB-OPAC. In der GBV-Ausprägung sind nicht alle Daten indexiert, die ich hier im Südwesten benötige (v.a. im Exemplarbereich), so dass der alte SWB-OPAC sicher noch einige Zeit gebraucht wird.
Im ISBN-Tool sieht es jetzt so aus, dass im Verbund-Array der GVK abgeprüft wird, beim Aufruf des Links aber vom GBV gleich auf "https://kxp.k10plus.de/DB=2.1/" weitergeleitet wird. Die Anzahl der dort verzeichneten Bestände hat aber nichts mit der Summierung über die alte Abfrage zu tun, Beispiel:
http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783770563739

Es wäre zu überlegen, ob der GBV-K10-OPAC (s. oben) nicht an die Stelle der alten http://gso.gbv.de/DB=2.1/-Abfrage treten sollte. Ob die K10Plus-Integration über SRU damit obsolet wäre, könnte man auch erörtern.

**Comment by zuphilip** [comment]
Was wir auf jeden Fall brauchen, ist die Möglichkeit nach einer K10plus-PPN zu suchen. Daneben müsste man prüfen ob die Suche nach den (alten) SWB-PPN immer noch geht.

Bei der Auflistung der einzelnen Suchergebnisse, scheint es in der Tat, dass momentan der K10plus vernachlässigbar ist, da keine weitere Information neben GBV und SWB gibt. Zudem scheint es noch keinen vereinigten K10plus-OPAC zu geben. Im GBV-OPAC dürften Titel fehlen mit nur Bestand im SWB und im SWB-OPAC dürften die Titel mit nur Bestand im GBV fehlen.

Die weitergeleitete gso.gbv.de-URL können wir natürlich dann auch anpassen.

**Comment by tkees** [comment]
Nein, der GBV-OPAC firmiert nicht nur in der Adresse als "K10plus", er führt auch unikalen Bestand aus dem SWB, z.B. https://kxp.k10plus.de/DB=2.1/PPNSET?PPN=1485125022
Eigentlich ist der GVK nun der K10Plus-Katalog, der sogar Exemplardaten des SWB aufführt und indexiert, z.B. (diesmal über die Signatur): https://kxp.k10plus.de/DB=2.1/CMD?ACT=SRCHA&IKT=1004&TRM=sig+2014-5668
Es werden zwar nicht alle lokalen Felder indexiert, er beinhaltet aber m.E. alle Daten (im Gegensatz zum SWB-OPAC, der nur die SWB-Daten aufführt).
Ich würde die K10Plus-Erweiterung herausnehmen und den GVK auf der neuen Adresse ansprechen. Wie man ihn nennt, ist dabei ziemlich unerheblich.

Grüße
Thomas

**Comment by zuphilip** [comment]
Okay, danke für die Erklärung.

> Ich würde die K10Plus-Erweiterung herausnehmen und den GVK auf der neuen Adresse ansprechen. Wie man ihn nennt, ist dabei ziemlich unerheblich.

Einverstanden. Als Benennung würde ich `GVK (K10plus)` vorschlagen.

Zusätzlich würde ich im Hintergrund die SRU-Schnittstelle vom GBV mit derjenigen vom K10plus austauschen. Damit sollte sich dann auch die Zählung der Bestände anpassen.

(Langfristig könnte man sich überlegen, ob man dann den eigenen SWB-Eintrag noch benötigt.)

**Comment by zuphilip** [comment]
@tkees Kannst Du einmal die neue Version testen? Ich habe jetzt den K10plus fertig eingebaut und den GBV-Katalog stattdessen herausgenommen.
