### ISSUE TITLE
Daten aus dem SWB-Katalog werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by tkees** [UB-Mannheim/malibu#114]
Trotz Bestand keine Anzeige der SWB-Daten mehr
http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=978-0-19-881479-5
http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=978-1-138-09138-2
http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=978-3-89861-557-0

Update: wahrscheinlich nur die Schnittstelle, sorry

**Comment by zuphilip** [comment]
Hat sich das erledgit @tkees ? Falls ja, dann kann man das Issue wieder schliessen, falls nein, brauche ich genauere Informationen, was nicht funktioniert.

**Comment by tkees** [comment]
Hat sich erledigt. War nur ein temporärer Fehler.
