### ISSUE TITLE
RVK-Notationen alphabetisch sortieren lassen

### ISSUE THREAD

**Issue by vossviola** [UB-Mannheim/malibu#115]
… für eine bessere Übersichtlichkeit. :)

**Comment by zuphilip** [comment]
@vossviola Hast Du nochmals das Beispiel zum Testen?

Ein zusätzliches `sort` hier sollte genügen: https://github.com/UB-Mannheim/malibu/blob/d13579d92bce2bfd61b92e240098545a34009c3f/isbn/rendering.js#L40

**Comment by vossviola** [comment]
dies war das Beispiel:
http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783958095229

**Comment by zuphilip** [comment]
Okay, versuche es nochmals aus und lade die Seite neu.
