### ISSUE TITLE
PPN-Suche im K10plus funktioniert nicht immer

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#116]
Teilweise funktioniert die PPN-Suche im K10plus, z.B. für die elektronische Ressource [1684971225](https://data.bib.uni-mannheim.de/malibu/isbn/k10plus.php?ppn=1684971225), aber nicht für die parallele Druckausgabe [1683942027](https://data.bib.uni-mannheim.de/malibu/isbn/k10plus.php?ppn=1683942027). Es fällt auf, dass die gedruckte Version im SWB aber nicht im GBV vorhanden ist: http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=1684971225&INDEXSET=21 .

Werden aktuell evt. alle K10plus-PPN, welche nur im SWB Bestand haben, nicht gefunden?

Ein möglicher Grund könnte sein, dass wir aktuell in der SRU-Schnittstelle die [Datenbank](https://wiki.k10plus.de/display/K10PLUS/Datenbanken) `gvk` verwenden. [Jetzt lese ich aber](https://wiki.k10plus.de/display/K10PLUS/SRU), dass evt. die Datenbank `opac-de-627` passender sein könnte. Hier funktioniert dann auch schon einmal der Abruf der oben genannten PPN: http://sru.k10plus.de/opac-de-627?version=1.1&operation=searchRetrieve&query=pica.ppn%3D1683942027&maximumRecords=10

@nichtich Für sachdienliche Hinweise bin ich dankbar.

**Comment by nichtich** [comment]
Das Datenbankkürzel für den gesamten K10Plus (SWB + GBV) ist `k10plus`: http://sru.k10plus.de/k10plus?version=1.1&operation=searchRetrieve&query=pica.ppn%3D1683942027&maximumRecords=10

**Comment by zuphilip** [comment]
Aber da habe ich von aussen keinen Zugriff: "Access to specified database denied" bzw. `info:srw/diagnostic/1/236`. Ich will aber auch nicht katalogisieren sondern nur lesen. Ist da nicht evt. opac-de-627 genau die richtige Datenbank?
> k10plus | K10plus-Katalogisierungsdatenbank
> opac-de-627 | K10plus-Verbundkatalog

**Comment by zuphilip** [comment]
@nichtich Ich habe mal einen PR daraus gemacht.
