### ISSUE TITLE
Vorgänger/Nachfolger Informationen aufnehmen

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#126]
Die Vorgänger/Nachfolger Informationen sind teilweise in den Verbunddaten enthalten und verknüpft inklusive alter/neuer ISBN, Z.B.
```
780 00$iVorangegangen ist$aJarass, Hans D., 1945 - $tGrundgesetz für die Bundesrepublik Deutschland. f$b15. Auflage$dMünchen : C.H. Beck, 2018$hXXVI, 1433 Seiten$w(DE-627)1015874517$w(DE-576)501218777$z9783406723698
```
bzw.
```
785 00$iGefolgt von$aJarass, Hans D., 1945 - $tGrundgesetz für die Bundesrepublik Deutschland. s$b16. Auflage$dMünchen : C.H. Beck, 2020$hXXV, 1434 Seiten$w(DE-627)1677302232$z9783406748752$z3406748759
```
Beim Bestand dürfen diese Ausgaben nicht gezählt werden, aber für die Sacherschließung sind diese ebenfalls relevant. Wie soll man dies hier im Tool berücksichtigen? Am Einfachsten wäre es einfach einmal mit einem Link auf das Tool mit der anderen ISBN an geeigneter Stelle einzubinden. Vielleicht gibt es aber auch andere und bessere Ideen...

**Comment by zuphilip** [comment]
Hier mal eine Idee für eine Einbindungen eines Links:
![grafik](https://user-images.githubusercontent.com/5199995/95215273-1671c680-07f1-11eb-8225-cb50fea6888a.png)

**Comment by zuphilip** [comment]
Beispiel mit Vorgänger und Nachfolger: https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783406732829

**Comment by tkees** [comment]
Das ist eine nette Idee @zuphilip. Viel "schlauer" kann man das vermutlich auch nicht anzeigen, aber um ehrlich zu sein, bin ich aus meiner Kenntnis des SWB (bzw. K10plus)-Katalogs der Meinung, dass da nicht viel zu holen ist. Im Gegensatz zu Periodika mit Ihren Iterationen sind diese Verknüpfungen extrem selten, da fakultativ und überhaupt erst mit RDA theoretisch eingeführt. Folgeauflagen werden ohnehin nicht verknüpft, sondern wären nur über den normierten Sucheinstige zu "fangen". Nur bei Änderungen, die die Werkgrenze überschreiten, kann verknüpft werden, was aber auch eher selten geschieht.
In diesem Beispiel gibt es überhaupt keine Relationen (was nicht nur damit zusammenhängt, dass es sich um Altdaten handelt):
https://swb2.bsz-bw.de/DB=2.1/CMD?ACT=SRCHA&IKT=1016&SRT=YOP&TRM=tst%3Abetriebswirtschaftliche+steuerlehre+per%3Akussmaul+not+tit%3Aarbeitsbuch+bbg%3Aaa*
Damit will ich sagen: kann man machen, man sollte aber m.E. nicht zu viel Energie hinein stecken.

**Comment by zuphilip** [comment]
Erst Version läuft mal schon und ergibt beim Beispiel oben:

![grafik](https://user-images.githubusercontent.com/5199995/127901436-2e76a43f-ad68-429d-a184-709f47e6e222.png)

Fügt nicht die DNB öfters diese Relationen jetzt ein? Ich habe hier in einer Liste von juristischen (deutschsprachigen) Lehrbüchern etliche von dieser Sorte gefunden. Wir können das ja jetzt weiter beobachten.

**Comment by tkees** [comment]
Dachte ich mir, dass in den Rechtswissenschaften am meisten zu holen ist. Da gibt es besondere RDA-Arbeitsunterlagen, und die Erschließung/Relationenbildung geht teilweise über die in den anderen Disziplinen hinaus.
Wie gesagt: sollte nicht defätistisch sein :-)

**Comment by zuphilip** [comment]
Es gibt aber auch andere Beispiele wie https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783662622209 (Springer / Technik), https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783658327743 (Springer / Excel) oder https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783648149386 (Führung / Haufe). Wann die ISBNs zu Vorauflage oder Folgeauflage katalogisiert werden, kann ich aber nicht sagen. Ich finde dies aber prinzipiell eine gute Sache und jetzt wird es zumindest schon mal sichtbar, wenn es solche Informationen gibt. Aber viel mehr Arbeit will ich da aktuell nicht hineinstecken.
