### ISSUE TITLE
Ersatz für SwissBIB

### ISSUE THREAD

**Issue by tkees** [UB-Mannheim/malibu#132]
Da SwissBib im Frühjahr eingestellt wurde (https://swissbib.blogspot.com/2020/11/zur-einstellung-der-swissbib.html) stellt sich die Frage, ob man die Schweiz aus der Bestandsabfrage herausnimmt oder auf swisscovery umstellt (https://swisscovery.slsp.ch)

Gibt es da schon jemanden, die/der da dransitzt?  :-)
Schönen Gruß, Thomas Kees

**Comment by stweil** [comment]
Bietet swisscovery eine geeignete Schnittstelle? Auf die Schnelle habe ich keine gefunden.

**Comment by zuphilip** [comment]
Der neue Katalog fußt auf Alma/Primo und daher sollte es auch eine SRU-Schnittstelle wie bei uns geben. In der Tat finde ich gerade hier die entsprechenden Informationen: https://slsp.ch/de/metadata von SLSP aus und ich gehe davon aus die Daten aus SLSP dem entsprechen, was man in swisscovery sieht. (Dann wären dies einfach etwas angepasste Namen für die Alma- und Primo-Instanz.) Das versuche hier gleich mal einen Test zu machen, ob die Schnittstelle entsprechend funktioniert...

**Comment by zuphilip** [comment]
Erste Version für den neuen Katalog von der Schweiz ist implementiert. :fireworks: Bitte einmal testen.

Soweit ich sehe, werden über die SRU-Schnittstelle keine Bestandsangaben ausgeliefert (was aber eigentlich möglich wäre). Daher sieht man aktuell überall die 0en beim Bestand in der Schweiz.

**Comment by tkees** [comment]
Toll, Philipp! Das ist auf einem guten Weg, aber noch nicht perfekt. Einige Stichproben liefern unterschiedliche Erfolge. In allen Fällen sind Schlagwörter vorhanden. Ein Problem der "Stelligkeit" scheint es mir nicht zu sein.
Vielleicht helfen die Beispiele:

nein:
9788373265752
https://swisscovery.slsp.ch/permalink/41SLSP_NETWORK/1ufb5t2/alma991062159919705501
9788366470163
https://swisscovery.slsp.ch/permalink/41SLSP_NETWORK/1ufb5t2/alma991047225429705501

ja:
3938400080
3906765199
3050025867
9783412230050

**Comment by zuphilip** [comment]
Danke für das Testen @tkees! Soweit ich das sehe, funktionieren aber auch die ersten zwei Beispiele, etwa https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9788366470163 , aber es dauert sehr lange. Die Abfrage an den Schweizer Katalog dauert ca. 1 Minute, aber dann erscheinen dort auch die Schlagworte und die DDC-Stelle. Versuche es aus.

Ein solche lange Antwort ist natürlich auch nicht gut, aber dies würde dann eher am Schweizer Katalog bzw. deren SRU-Schnittstelle liegen. Da sehe ich nicht viel, was ich hier ändern könnte.

**Comment by tkees** [comment]
Danke, @zuphilip . Ich war tatsächlich zu ungeduldig, aber ich befürchte, soooo geduldig werde ich in diesem Leben auch nicht mehr werden (gerade 48 Sek.). Kann man sicher nichts machen, und besser als die abgehängte Schnittstelle von SwissBIB ist es vermutlich schon. Manchmal kommen die Ergebnisse ja auch schneller :-)

**Comment by zuphilip** [comment]
Möglicherweise könnte SLSP oder ExLibris noch etwas machen, da so eine lange Antwortzeit sicherlich nicht normal ist. Da ich auf eine andere E-Mail aber noch keine Antwort bekommen habe (auch tw. etwas ungeduldig bin;-), bin ich aber etwas skeptisch, ob meine Anfragen bei denen so großes Gewicht haben. Die Anfragen an SLSP kann aber auch jede*r schreiben und insbesondere von Projektbibliotheken aus könnte dies mehr Gehör finden.

Momentan bleibt es aber aber, dass auf meiner Seite keine direkten Handlungsoptionen gibt. Wir können nur hoffen, dass diese Fälle selten sind oder dann so verzwickt, dass man genügend lange auf der Seite bleibt, bis das Resultat von der Schweiz über SRU auch eintrudelt.

**Comment by zuphilip** [comment]
Kurzer Zwischenstand: Die SRU-Anfrage im Browser https://swisscovery.slsp.ch/view/sru/41SLSP_NETWORK?version=1.2&operation=searchRetrieve&recordSchema=marcxml&query=alma.mms_tagSuppressed=false+AND+(alma.all=9788366470163) geht auch schnell, aber ich glaube, dass diese nicht ganz sauber abgeschlossen wird und daher die Verbindung länger geöffnet bleibt in `file_get_contents`. Das muss ich aber noch verifizieren... Auf die Schnelle habe ich einmal von der Anfrageseite ein Timeout von 3s eingefügt und damit geht die Abfrage in malibu m.E. genügend schnell. Das könnte aber auch unerwünschte Nebenwirkungen haben...

**Comment by zuphilip** [comment]
Update zu den Bestandsdaten: Dies scheint technisch nicht möglich zu sein, da die Bestandsinformationen nicht in der Netzwerkzone liegen sondern in den einzelnen IZs.
