### ISSUE TITLE
OBVSG Z39.50 mit SRU ersetzt

### ISSUE THREAD

**Issue by smjwsk** [UB-Mannheim/malibu#140]
Die OBVSG hat den Zugriff über Z39.50 mit Abschaltung von Aleph dieses Jahr endgültig auslaufen lassen. Nutzer·innen aus unserem Verbund ist aufgefallen, dass malibu noch die ehemalige Z39.50 Schnittstelle verwendet

Infos zu dem SRU-Endpoint und Kontakt für Zugriffsmöglichkeiten sind auf den [Verbundseiten der OBVSG zu SRU dokumentiert](https://www.obvsg.at/services/verbundsystem/sru).

**Comment by zuphilip** [comment]
Danke für den Hinweis. Ja, das sollt mal angepasst werden.

**Comment by zuphilip** [comment]
Testcases für die Anpassung:
1. https://data.bib.uni-mannheim.de/malibu/isbn/obvsg.php?isbn=9783422989498 Dies sollte dann aufrufbar werden.
2. https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783422989498 Hier sollte bei OBVSG dann auch etwas angeigt werden. Konkret sollten die Schlagwörter dann funktionieren, möglicherweise auch die Bestandsangaben (aber dies kommt auch auf die Konfiguration bei Alma im OBVSG drauf an).
3. https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?ppn=99146820502203331&verbund=OBVSG oder ähnliche Aufrufe sollten dann funktionieren.

**Comment by zuphilip** [comment]
@smjwsk Inwiefern unterschieden sich die beiden Datenpools OBV-LIT und OBV-PARTNER? Sind im zweiten auch Bestandsdaten enthalten?

**Comment by michaelfreiberg** [comment]
Aktuell kommt es zu Timeouts beim Abruf von https://data.bib.uni-mannheim.de/malibu/isbn/obvsg.php?isbn=...

**Comment by zuphilip** [comment]
Mit #141 sollte zumindest die öffentlich frei verfügbaren Daten wieder funktionieren vom OBVSG.

**Comment by zuphilip** [comment]
Es scheint aktuell nicht realistisch zu sein, dass wir an die Bestandsdaten beim OBVSG über SRU dran kommen. Daher ist jetzt hier alles erledigt und Issue kann geschlossen werden.
