### ISSUE TITLE
"Aufsummierte" RVK-Notationen

### ISSUE THREAD

**Issue by vossviola** [UB-Mannheim/malibu#146]
Könnte man eine Zeile am Ende der Tabelle ergänzen, in der alle RVK-Notationen gesammelt aufgeführt werden, die in den Verbünden gefunden wurden?

Für 
https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=%203-7705-1862-4
wäre das dann z.B.: 
ET 350, ET 400, ET 510, GC 6904

**Comment by zuphilip** [comment]
Was wäre dann der Anwendungsfall dafür?

Es gibt ja schon die Möglichkeit auf die "RVK aggregiert" umzuschalten und da hat man dann auch einen Überblick über alle in den Verbünden gefundene RVK-Stellen inklusive der (Sub-)Baumstruktur und Bezeichnungen. Im Deinem Beispiel:

![grafik](https://user-images.githubusercontent.com/5199995/223958049-deb6829a-5754-46c9-8a50-efc8dc1c5f46.png)

Wäre Dein Vorschlag zusätzlich zu dieser Funktion bzw. was kann man damit aktuell nicht machen aber mit der neuen Zeile wäre es dann möglich?

**Comment by zuphilip** [comment]
Okay, alles klar.

@vossviola Wenn ihr das gleich für eine ganze Liste macht, dann probiere gerne auch einmal das [neue Tool für das Anreichern](https://data.bib.uni-mannheim.de/malibu/tools/ppnListe.html) aus:
![grafik](https://user-images.githubusercontent.com/5199995/224260857-6daf701f-8421-4ff5-8564-c0a4dad1006d.png)
