### ISSUE TITLE
Testen für neues Release 1.0.2

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#32]
Gerne würde ich ein [neues Release](https://github.com/UB-Mannheim/malibu/releases) veröffentlichen mit den ganzen Verbesserungen der letzten Wochen. Dazu werde ich auch in den nächsten Tagen etwas mehr testen. Der neue Stand 2ab505b86e557ae2ea7d5ce0cc63d63ba173d9b0 ist deployed:

http://data.bib.uni-mannheim.de/services/

Alle sind herzlich eingeladen zum Testen @kba @stweil @tkees . Für jeden fehlgeschlagenen Testfall oder Verbesserungsvorschlag bitte einen [neuen Issue](https://github.com/UB-Mannheim/malibu/issues/new) eröffnen.

**Comment by stweil** [comment]
Is there a chance for automated tests which can also be included in the Travis check? https://docs.travis-ci.com/user/gui-and-headless-browsers/ includes some hints for testing of web applications.

**Comment by stweil** [comment]
@zuphilip, the Apache2 error log `/var/log/apache2/error.log` on the server shows several issues. Here an example:

    PHP Notice:  Use of undefined constant OBVSG_URL - assumed 'OBVSG_URL' in /var/www/html/malibu/isbn/obvsg.php on line 31, referer: http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?ppn=AC00589949&verbund=OBVSG

**Comment by zuphilip** [comment]
* Automated tests will be appreciated in the future and there exists already some work in this direction: https://github.com/kba/malibu/tree/unit-test
 * Because of the renaming problem I also had to rename the variables in the hidden `conf.php` manually. I think the apache logs are from before changing these files.

**Comment by stweil** [comment]
There are also new PHP messages:

    [Tue Feb 09 20:42:20.497881 2016] [:error] [pid xxx] [client xxx] PHP Notice:  Undefined variable: nrArray in /var/www/html/malibu/bnb/bnb.php on line 76, referer: http://data.bib.uni-mannheim.de/malibu/bnb/recherche.php?ddcgruppe%5B%5D=000%2C001%2C002%2C003
    [Tue Feb 09 20:42:20.498118 2016] [:error] [pid xxx] [client xxx] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/malibu/bnb/bnb.php on line 76, referer: http://data.bib.uni-mannheim.de/malibu/bnb/recherche.php?ddcgruppe%5B%5D=000%2C001%2C002%2C003

**Comment by zuphilip** [comment]
My tests worked good and therefore I just release version 1.0.3: https://github.com/UB-Mannheim/malibu/releases/tag/1.0.2 . Please keep report any issues as individual issues I will close this one here.
