### ISSUE TITLE
Bestellinformation automatisch kopieren

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#35]
Momentan öffnet sich ein kleines Fenster mit der Bestellinformation, welche dann jeweils händisch markiert und kopiert werden muss:

![bestellinfo](https://cloud.githubusercontent.com/assets/5199995/13018321/2da02fe4-d1c9-11e5-8f6e-d44440d69789.jpg)

Kann man das Markieren der gesamten Bestellinfo und in die Zwischenablage kopieren bereits beim Klicken automatisch machen? Im Prinizip müsste man dann die Bestellinformation gar nicht mehr anzeigen oder zumindest solch eine Anzeige optional machen...

Ansatz evt. http://www.jqueryscript.net/form/Copy-Entire-Textarea-To-Clipboard-Using-jQuery-Copyme.html

**Comment by zuphilip** [comment]
https://clipboardjs.com/ bzw. https://github.com/zenorocha/clipboard.js

Dies scheint wesentlich mehr verbreitet zu sein und auch aktiv entwickelt zu werden. Einzig mit Safari funktioniert das kopieren noch nicht ganz (vernachlässigbar für mich).

**Comment by kba** [comment]
https://clipboardjs.com/ funktioniert gut, in mehreren Projekten verwendet. Safari wird schon unterstützt, aber mit einem etwas anderen Mechanismus.

**Comment by kba** [comment]
Mit clipboard.js:

Einmal nach dem Laden der Seite:

```
new Clipboard(".clipboard-button");
```

Und im HTML:
```
<button data-clipboard-text="text to copy" class="clipboard-button">Copy-me</button>
```

Dann wird aus dem `data-clipboard-text` attribut in die Zwischenablage bei Klick kopiert.
