### ISSUE TITLE
[isbn] DDC link broken

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#5]
The ddc link seems to be broken because the server http://www.dewey.info/ is down. Alternatives?

**Comment by stweil** [comment]
dewey.info is still on-line, but no longer working properly. Maybe it needs a restart and asking OCLC who operate it might help.

**Comment by zuphilip** [comment]
Thank you for the information. I wrote the <a href="http://datahub.io/de/dataset/dewey_decimal_classification">maintainer of the LOD</a> an email.

**Comment by zuphilip** [comment]
I found this tweet from OCLC (2015-05-22):
<blockquote>
Dewey.info  continues to be offline for database maintenance. Current estimate is it will be back online sometime in July
</blockquote>
https://twitter.com/OCLC/status/601760351147970560

**Comment by zuphilip** [comment]
Update from their OCLC's page (2015-06-09):
<blockquote>There is no current projected date for the return of Dewey.info right now.</blockquote>

http://www.oclc.org/developer/news/2015/dewey-down.en.html

**Comment by zuphilip** [comment]
For the first 3 digits we could use the list provided by wikipedia: https://en.wikipedia.org/wiki/List_of_Dewey_Decimal_classes

**Comment by zuphilip** [comment]
Okay, here is [another online service](http://deweysearchde.pansoft.de/webdeweysearch/mainClasses.html) for the German translation of the DDC, which we can try to use to link and/or resolve the numbers into some class names, for example: http://deweysearchde.pansoft.de/webdeweysearch/executeSearch.html?lastScheduleRecord=515.48&lastTableRecord=&query=515.48
