### ISSUE TITLE
[isbn] führendes Leerzeichen in der Sacherschließungstabelle entfernen

### ISSUE THREAD

**Issue by vossviola** [UB-Mannheim/malibu#59]
In den Spalten RVK-Notation, DDC-Notation und Schlagwörter werden die Einträge mit einem Leerzeichen eingeleitet, das eigentlich nicht notwendig ist. 
(Und das bei Einträgen, die länger als eine Zeile sind, zu einer unschönen Einrückung führen.

[Was für die Abteilung "B-Note" und "Wenn man mal Langeweile hat". :)]

![malibu_isbn_rvk_leerzeichen](https://cloud.githubusercontent.com/assets/19427558/17735335/d71d7e96-6481-11e6-8447-f0a9cf7f6a7e.png)

**Comment by zuphilip** [comment]
Okay, das stimmt. Ich habe dafür einmal ein neues Label "minor" vergeben. Wenn Du den Fehler findest, dann kannst Du uns gerne auch einen Fix schicken.

In [dem Beispiel](http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783150108390+or+315010839X) fallen mir aber auch die Schlagwörter vom GBV auf, die merkwürdig aussehen. Das könnte man auch einmal genauer ansehen...

**Comment by zuphilip** [comment]
Das Leerzeichen wurde in 3cf2482 korrigiert und die Schlagwörter in 3796eec.
