### ISSUE TITLE
Vollständiger RVK-Pfad im Mouseover

### ISSUE THREAD

**Issue by vossviola** [UB-Mannheim/malibu#63]
Wenn man mit der Maus über eine RVK-Notation geht, werden die Bezeichnung der jeweiligen Klasse und die darüberliegende Ebene angezeigt.
Beispiel ET 450: "Bedeutung (semantische Komponentenanalyse, semantisches Merkmal) <-- Einzelprobleme".
(Z.B. bei http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=9783942158664.)

Ein Münsteraner Kollege schlägt vor, hier den gesamten "Pfad" der Klasse anzugeben, für mehr Orientierung gerade in tiefen Systematiken. 
Für ET 450 wäre das dann z.B. "Bedeutung (semantische Komponentenanalyse, semantisches Merkmal) <-- Einzelprobleme <-- Synchrone Semantik <-- Semantik und Lexikologie <-- Einzelgebiete der Sprachwissenschaft, Sprachbeschreibung <-- Allgemeine und vergleichende Sprach- und Literaturwissenschaft. Indogermanistik. Außereuropäische Sprachen und Literaturen".

Das wäre dann sozusagen "wie RVKVisual, nur als Mouseover". :)
(https://www.kobv.de/open-source-tool-rvk-visual/)
(Beispiel im KOBV: http://portal.kobv.de/uid.do?query=b3kat_BV040995956)

**Comment by zuphilip** [comment]
Ich bin etwas skeptisch, ob der gesamte Pfad dann nicht das Ganze wieder unübersichtlich macht. Persönlich klicke ich dann lieber auf den Link um mir die Notation im Baum anzusehen, anstatt das Mouseover zu lesen. Die RVK ist aber in verschiedenen Fächer auch sehr unterschiedlich: Die RVK ist beispielsweise [in der Informatik](http://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/SQ%20-%20SU) sehr flach augebaut und die Klassenbezeichnungen der einzelnen Klassen sind meist bereits aussagekräftig. Vielleicht könnte man aber die angezeigte Tiefe der RVK einstellbar machen.

Bei dem Beispiel oben erscheinen mir insbesondere die untersten beiden Klassen (Einzelgebiete der Sprachwissenschaft, Sprachbeschreibung <-- Allgemeine und vergleichende Sprach- und Literaturwissenschaft. Indogermanistik. Außereuropäische Sprachen und Literaturen) klar zu sein.

Was meint ihr dazu?

**Comment by vossviola** [comment]
Ja, stimmt, in einigen Systematiken könnte es dann ausufern. Mein Kollege könnte sich dazu z.B. eine Zweiteilung der Anzeige vorstellen, so wie in der RVK-online: links die Ergebnisse des Tools, rechts der RVK-Baum. Dann muß man nicht den Browser-Tab wechseln.

Vermutlich liegen diese Überlegungen darin begründet, daß wir hier in Münster noch RVK-Newbies sind und noch nicht fließend RVK sprechen; vielleicht gibt sich das, wenn wir mehr "drin" sind. :)
Wir denken nochmal weiter drüber nach und melden uns, wenn uns dazu noch etwas einfällt bzw. wir unseren Vorschlag konkretisieren können.

**Comment by zuphilip** [comment]
Prinzipiell auch möglich sind erweiterte Tooltips mittels einer geeigneten JavaScript Bibliothek, z. B. http://iamceege.github.io/tooltipster/ . Dann könnte man die die verschiedenen Hierarchiestufen auch jeweils auf neuen Zeilen beginnen und ggf. noch weiteres HTML benutzen um die Darstellung zu vereinfachen...

Wenn jemand Lust hat ein Mockup zu erstellen oder (besser) eine Lösung vorzuschlagen dann kann ich mir vorstellen dies einzubauen oder konfigurierbar zu machen. Evt. eignet sich auch https://jsfiddle.net/ für einen Vorschlag zu diskutieren.

**Comment by zuphilip** [comment]
Hier mal ein Vorschlag von mir zu dem Thema: Es wäre vorstellbar, neben den normalen Tabellenspalten auch noch verteckte Spalten vorzuhalten, welche durch einen Klick aktiviert werden könnten und dann auf Grund der Daten der verschiedenen Verbünde (welche dann wohl meist alle da sind von den ganzen asynchronen Calls) eine aggregierte Ansicht oder weitere Informationen anzuzeigen.

Beispielsweise [bei dem Treffer](http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=978-3-8006-4582-4) mit der normalen Ansicht:

![rvk-normal](https://cloud.githubusercontent.com/assets/5199995/21753145/9ba4e0f8-d5e6-11e6-9800-8ac72aaccaa8.png)

in die aggregierte RVK-Ansicht wechseln:

![rkv-aggregiert](https://cloud.githubusercontent.com/assets/5199995/21753152/c9adca8c-d5e6-11e6-9f76-a16057b5e6cf.png)

Dies wäre dann im Prinzip auch für die anderen Spalten (DDC, Schlagwörter) vorstellbar. Dabei könnte man auch noch weitere Daten berechnen (beispielsweise Mappings zwischen DDC und RVK versuchen).

Was meint ihr dazu?

**Comment by vossviola** [comment]
Das sieht nach einer guten Idee aus! "Zuschaltbar" für die, die's brauchen können, und nicht weiter störend für die, die's nicht brauchen.
Man könnte vielleicht noch ein paar Zeichen sparen, wenn man z.B. statt <=/=> und <- «/» oder ‹ verwendet, aber das ist ja dann nur Kosmetik. :)

Wie würde man das DDC-RVK-Mapping einbauen? (Wäre aus Münsteraner Sicht eher nachgeordnet, weil die DDC hier kaum eine Rolle spielt, aber an sich natürlich interessant.)

**Comment by zuphilip** [comment]
> Wie würde man das DDC-RVK-Mapping einbauen?

Grafisch könnte man dies ähnlich einbauen und von den Informationen stelle ich mir (im optimalsten Fall) so etwas wie folgt vor

"
5 x 338.973  ( 338 --> [QG ](url))
1 x 650
3 x 658.14 --> [QP 300](url)
2 x 658.15 Finanzmanagement --> [QP 700-QP 780](url)
1 x 658.1522 Kapitalbeschaffung --> [QP 750-QP 760](url)
"

Dies könnte dann vorallem für Fälle ohne RVK-Notationen nützlich sein.

**Comment by vossviola** [comment]
Ah, okay. Könnte in der Tat sehr nützlich sein!

**Comment by zuphilip** [comment]
Die Auswertung könnte man noch anders darstellen in einer Teilbaumansicht, etwa so:

"
Pädagogik
|-Didaktik und Methodik des Unterrichts
|-|-Didaktik einzelner Sachgebiete und Themen
|-|-|-Einzelne Unterrichtsfächer
|-|-|-|-Allgemeine Wirtschaftslehre
|-|-|-|-|-Allgemeines: **6 x DP 5300**

Wirtschaftswissenschaften
|-Allgemeine Betriebswirtschaftslehre
|-|-Aufbauelemente des Unternehmens
|-|-|-Investition und Finanzierung
|-|-|-|-Allgemeines: **7 x QP 700**
|-|-|-|-Finanzierung, Finanzplanung und Kontrolle: **7 x QP 710**
|-|-|-|-Kapitalbedarfsrechnung. Finanzplanung. Finanzkontrolle: **1 x QP 730**
|-|-|-|-Kapitalbeschaffung (Finanzierung i. e. S.)
|-|-|-|-|-Allgemeines: **7 x QP 750**
"
