### ISSUE TITLE
Update links to ebook packages

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/malibu#81]
For example in http://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=978-3-11-031622-3

![malibu-ebook-link](https://user-images.githubusercontent.com/5199995/31552175-fa4fefaa-b036-11e7-9d37-d7f46fbc325d.jpg)

there is a link from ZDB-2-DGG to

http://dispatch.opac.dnb.de/DB=1.2/CMD?ACT=SRCHA&IKT=8521&SRT=LST_os&TRM=ZDB-23-DGG

which has to be changed to

http://sigel.staatsbibliothek-berlin.de/nc/suche/?isil=ZDB-23-DGG

**Comment by huyvohcmc** [comment]
Hi @zuphilip, I would like to take this issue

**Comment by jpabeem** [comment]
I've fixed this issue because of Octoberfest, I hope my contribution is sufficient (first time contributing). Pull request is available soon.
