### ISSUE TITLE
Veraltete RVKs markieren

### ISSUE THREAD

**Issue by reretter** [UB-Mannheim/malibu#87]
Ist es möglich, gelöschte RVKs in malibu farblich hervorzuheben? Bisher werden alle in den Verbünden vergebenen RVKs angezeigt, selbst wenn sie veraltet sind und nicht mehr vergeben werden können. 
Im SWB sind gelöschte RVKs im Feld 012$b mit a gekennzeichnet. Lässt sich daraus eine Negativliste erstellen?

**Comment by zuphilip** [comment]
Als Plan könnte man folgende Punkte angehen:

1. Finde 2-3 Beispiele für veraltete RVK Stellen und auch Testbeispiele von Titelaufnahmen mit solchen veralteten Stellen
2. WinIBW
    a. Wie kann man in der WinIBW nach RVK-Stellen suchen?
    b. Kann man in der WinIBW nach RVK-Stellen mit speziellen `012$b` = a suchen?
    c. Wie kann Surchresultate aus der WinIBW exportieren?
    d. Sind dies nur gelöscht oder auch geänderte Stellen? Vgl. auch https://twitter.com/exwima/status/974184789489209344
3. RVK als Datendump
    a. Sind die gelöschten RVK-Stellen hier auch noch drin? Vgl. auch https://twitter.com/exwima/status/974185377727688711
    b. Sind die gelöschten RVK-Stellen speziell markiert?
    c.* Wie kann man nur die gelöschten/nicht-gelöschten RVK-Stellen abgreifen?

**Comment by exwima** [comment]
_Ich versuche mich an ein paar Antworten..._

**zu 3.: Änderungen bei RVK-Notationen und Datenlieferungen aus Regensburg:**

In den vierteljährlichen Update-Lieferungen der RVK werden meines Wissens folgende Fälle von Änderungen unterschieden:

- Neue RVK-Notation (neuer Notationsnormsatz, neue Identnummer)
- Löschung einer RVK-Notation (Markierung der Identnummer des Normsatzes als gelöscht)
- Änderung ohne Konzeptänderung, z.B. kleinere Korrekturen an der Benennung der Notation, zusätzliche Registerbegriffe (Notationsnormsatz wird mit den entsprechenden Änderungen in den Datenfeldern geliefert, Identnummer bleibt gleich)
- Änderung mit Konzeptänderung, z.B. Ausgliederung eines Themas in eine andere Notation (Notationsnormsatz mit alter Identnummer wird als gelöscht markiert, zusätzlich wird ein neuer Normsatz mit den aktualisierten Datenfeldern und neuer Identnummer für diese Notation geliefert)

--> Achtung: Im Fall einer Konzeptänderung kommt die Notation (als String) somit in zwei Normsätzen vor, die durch die Identnummer unterschieden werden.

Datenbestand zum Download: 
[https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online/rvk-download
](https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online/rvk-download)
Aktuelle Informationen zum Format der Datenlieferung, eine Übersicht der verschiedenen Änderungsfälle und ihrer Kennzeichnung im Update kann man sicher von der RVK-Koordinierungsstelle in Regensburg erhalten. Es gab dazu jedenfalls schon Präsentationen auf den Anwendertreffen.

Meiner Erinnerung nach wurde in der Diskussion auf dem Anwendertreffen 2016(?) von den Regensburger IT-Kollegen auch zugesagt, die gelöschten Notationsnormsätze mit einer entsprechender Kennzeichnung in der Datenbank zu erhalten. Dann könnte man evtl. den Gesamtabzug nutzen, um vor der Anzeige des Suchergebnisses in Malibu gelöschte / nicht vorhandene Notationen zu identifizieren und zu markieren.

Bei gelöschten RVK-Notationen scheint die RVK-API derzeit wohl weder Hierarchie noch Benennung zu liefern. Schon jetzt bleibt in diesen Fällen jedenfalls der Mouse-Over-Text in Malibu leer.

**Comment by exwima** [comment]
**zu 2.: WinIBW / SWB:**

Der SWB pflegt schon seit mehreren Jahren Normsätze für die RVK-Notationen anhand der Datenlieferungen aus Regensburg. Nach der Einführung von Identnummern wurden die "neuen" Notationsnormsätze eingespielt und gematcht. Eine Dokumentation des Datensatzformats, der Recherchemöglichkeiten und der Aktualisierung der Normsätze findet sich im "Katalogisierungshandbuch RVK": [https://verbund-swop.bsz-bw.de/frontdoor/index/index/docId/172](https://verbund-swop.bsz-bw.de/frontdoor/index/index/docId/172)

**a) Wie kann man in der WinIBW nach RVK-Stellen suchen?**
"f rvn ...",  Einschränkung auf Normsätze mittels "bbg tk*" oder "rec n;"
Beispiel: rec n; f rvn qm 300  --> findet den Normsatz für QM 300

**b) Kann man in der WinIBW nach RVK-Stellen mit speziellen 012$b = a suchen?**
"f svk a" sucht nach Satzverwendungskennzeichen a in Feld 012 $b , für die anderen Kennzeichen analog.

**c) Wie kann man Suchresultate aus der WinIBW exportieren?**
Manuell mit der download-Funktion (über Menü oder Befehl "dow"). Es können dabei die Treffer und das Format ausgewählt werden.
Beispiel:  dow 1-20 d  ---> Download des Treffers 1-20 der aktuellen Treffermenge im PICA3-Format

**d) Sind dies nur gelöschte oder auch geänderte Stellen?**

- Feld 012 $bn markiert die normierten RVK-Datensätze, die mit der RVK-Datenbank in Regensburg übereinstimmen.
- Feld 012 $ba wird im SWB bei RVK-Normsätzen erfasst, die keine Entsprechung mehr in der Regensburger RVK-Normdatenbank haben (veraltet, Fall "gelöschte Notation"). Seit der Einführung der Identnummern werden diese Sätze womöglich auch im SWB dauerhaft gespeichert. Früher wurden 012 $ba-Sätze meines Wissens gelöscht, sobald kein Titel mehr damit verknüpft war.
- Außerdem wird vom SWB 012 $bt bei Notationen vergeben, bei denen damit verknüpften Titel zu überprüfen sind. Die Notation existiert in diesem Fall noch, wird aber anders verwendet (Fall "Konzeptänderung"), weswegen es dann einen zweiten Normsatz mit der gleichen Notation, aber mit anderer Identnummer (und Kennzeichnung 012 $bn) gibt.

Oft (aber nicht immer) findet sich im SWB bei den 012$ba- und 012$bt-Normsätzen in Feld 909 übrigens ein erläuternder Hinweis.
Beispiel: 909 "Bitte mit dieser veralteten Notation nicht mehr verknüpfen, sie wurde ausdifferenziert. ZREDak"

**Comment by exwima** [comment]
**zu 1.: Beispiele:**

**Beispiele für gelöschte Notationen:**
- IS 2545 Vulgärsprache (SWB: 012 $ba)  
_Beispieltitel:_ Italo-Slang / Michael Blümke, ISBN 3-89416-945-1 
- IM 9400 Inselspanisch  (SWB: 012 $ba)
_Beispieltitel:_ Spanisch in Asien und Ozeanien / Steve Pagel, ISBN 978-3-631-60830-2
- ML 9390 Zaire  (SWB: 012 $ba, jetzt vermutlich ML 9348 Kongo (Demokratische Republik))
_Beispieltitel:_ Zaire und der Westen / Martin Schümer, ISBN 3-7713-0230-7
- US 5400	 Quasars (im SWB nicht mehr vorhanden, schon 2012 oder 2013 zu US 3420 „Aktive Galaxien“ verschoben)
_Beispieltitel:_ Quasar astronomy / Daniel W. Weedman, ISBN 0-521-30318-4

**Beispiele für Notationen mit geänderter Bedeutung:**
- CB 4800 Fachdidaktik (SWB: 012 $bt, wurde ausdifferenziert), 
neue Notationsbenennung: CB 4800 Allgemeines, Theorie, Geschichte, curriculare Fragestellungen, etc.
_Beispieltitel:_ Mit Kindern philosophieren / Gerhard Friedrich ..., ISBN 978-3-407-62829-9
   --> wäre jetzt vermutlich CB 4801 oder 4802, CB 4800 muss aber nicht "falsch" sein
- IS 3680 19. und 20. Jahrhundert (SWB: 012 $bt, diese Notation beinhaltet jetzt nur noch 19. Jh., 20. Jh. hat eine weitere Notation bekommen), 
_Beispieltitel:_ La linguistica italiana alle soglie del 2000 : (1987 - 1997) e oltre / a cura di Cristina Lavinio, ISBN 88-8319-686-4
- MS 3150 Frauenbewegung (SWB: 012 $bt, da es im Bereich Gender Studies große Veränderungen der Notationen gab)
_Beispieltitel 1:_ Gender and the media / Rosalind Gill, ISBN 978-0-7456-1915-6
     --> wäre jetzt wohl eher MS 3010; außerdem ist der Titel teilweise auch noch mit der nicht mehr vorhandenen Notation MS 3040 versehen 
_Beispieltitel 2:_ Die neue Frauenbewegung in Deutschland / Ilse Lenz (Hrsg.) 
    --> die Notation MS 3150 passt weiterhin, der Titel müsste aber zumindest im SWB mit dem neuen Normsatz (ebenfalls MS 3150, aber neue Identnummer) verknüpft werden

**Beispiele für Notationen, die im SWB womöglich fälschlicherweise mit 012 $ba gekennzeichnet sind:**

- UQ 6140
- MR 2450

Hier kann ich nicht erkennen, warum für diese Notationen im SWB jeweils ein $bn und ein $ba-Normsatz existiert. Laut RVK-Online sind beide Notationen gültig und die Benennung stimmt soweit auch überein. Womöglich war das Matching beim Erstimport der Identnummern aufgrund kleiner Abweichungen nicht erfolgreich, weswegen der Regensburger Datensatz neu eingespielt und der vorhandene Datensatz als veraltet gekennzeichnet wurde.

**Comment by reretter** [comment]
Herzlichen Dank für die ausführlichen Antworten und Beispiele. Wir prüfen das und melden uns, wenn wir weiter sind.

**Comment by zuphilip** [comment]
Entgegen dem ursprünglichen Plan ist es wesentlich leichter das Resultat der RVK-API in den Fällen von gelöschten Notationen weiter auszuwerten. Hier liefert die RVK-API eine Fehlermeldung in JSON zurück. Dies kann man dann hernehmen um diesen Knoten eine spezielle Klasse zuzuordnen und damit farblich hervor zu heben. Ich habe dies einmal schnell ausgestet, z.B. https://data.bib.uni-mannheim.de/malibu/isbn/suche.html?isbn=%20978-0-7456-1915-6 . Die anderen Änderungen wie oben beschrieben werden dabei nicht hervorgehoben, aber es wird ja immer die aktuelle Version von den Konzepten angezeigt. Daher sollte dies für die Neuvergabe von RVKs auch genügen.
